accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', CreateUserView.as_view(), name='signup'),
    path('done/', CreateDoneUserView.as_view(), name='done'),
    path('createTeacher/', CreateTeacherView.as_view(), name='teacher'),
    path('createStudent/', CreateStudentView.as_view(), name='student'),
    path('edit/<int:pk>', UpdateUserView.as_view(), name='edit'),
    path('<int:pk>/', TeacherDetailView.as_view(), name='teacher_datail'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    email = models.EmailField(blank=True)
    phone_number = models.CharField(max_length=11, blank=True)
    GENDER_MAIL, GENDER_FEMAIL = 0, 1
    GENDER_OPTION = (
        (GENDER_MAIL, '남성'),
        (GENDER_FEMAIL, '여성')
    )
    sex = models.SmallIntegerField(choices=GENDER_OPTION, null=True)
    USER_TEACHER, USER_STUDENT, USER_PARENT = 0, 1, 2
    USER_TYPE = (
        (USER_TEACHER, '선생님'),
        (USER_STUDENT, '학생'),
        (USER_PARENT, '학부모'),
    )
    user_type = models.SmallIntegerField(choices=USER_TYPE, null=True)

    class Meta(AbstractUser.Meta):
        swappable = 'AUTH_USER_MODEL'

    def is_teacher(self):
        return hasattr(self, 'teacher') and self.user_type == User.USER_TEACHER

    def is_student(self):
        return hasattr(self, 'student') and self.user_type == User.USER_STUDENT


class Teacher(models.Model):
    user = models.OneToOneField('accounts.User', on_delete=models.CASCADE, related_name='teacher')
    university = models.CharField(max_length=20)
    subjects = models.CharField(max_length=20)
    age = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.user.first_name


class Student(models.Model):
    user = models.OneToOneField('accounts.User', on_delete=models.CASCADE, related_name='student')
    school = models.CharField(max_length=15)
    year = models.CharField(max_length=5)

    def __str__(self):
        return self.user.first_name

accounts/forms.py
from django.contrib.auth import authenticate

from accounts.models import User, Teacher, Student
from django.contrib.auth.forms import UserCreationForm
from django import forms


class CreateUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'sex',
            'user_type',
        )

    def __init__(self, request=None, *args, **kwargs):
        self.request = request
        super(CreateUserForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        ret = super(CreateUserForm, self).save(commit)
        if commit:
            self.user = authenticate(
                self.request,
                username=self.cleaned_data.get('username'),
                password=self.cleaned_data.get('password2')
            )

        return ret


class TeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        exclude = ('user',)
        fields = '__all__'

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(TeacherForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        self.instance.user = self.user
        return super(TeacherForm, self).save(commit=commit)


class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        exclude = ('user',)
        fields = '__all__'

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(StudentForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        self.instance.user = self.user
        return super(StudentForm, self).save(commit=commit)

accounts/views.py
from django.http import JsonResponse, Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView, DetailView
from django.views.generic.edit import CreateView, UpdateView
from .forms import CreateUserForm, TeacherForm, StudentForm
from .models import User
from django.contrib.auth import login as auth_login


class CreateUserView(CreateView):
    template_name = 'accounts/signup.html'
    form_class = CreateUserForm

    def get_form_kwargs(self):
        kwargs = super(CreateUserView, self).get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def post(self, request, *args, **kwargs):
        return super(CreateUserView, self).post(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        return super(CreateUserView, self).get(request, *args, **kwargs)

    def get_success_url(self):
        user_type = self.request.POST.get('user_type')
        if user_type == str(User.USER_TEACHER):
            return reverse_lazy('accounts:teacher')
        elif user_type == str(User.USER_STUDENT):
            return reverse_lazy('accounts:student')

    def form_valid(self, form):
        ret = super(CreateUserView, self).form_valid(form)
        auth_login(self.request, form.user)
        return ret


class CreateDoneUserView(TemplateView):
    template_name = 'accounts/signup_done.html'


class UpdateUserView(UpdateView):
    template_name = 'accounts/account_update.html'
    form_class = CreateUserForm
    model = User
    success_url = reverse_lazy('home')


class CreateTeacherView(CreateView):
    template_name = 'accounts/create_teacher.html'
    form_class = TeacherForm
    success_url = reverse_lazy('accounts:done')

    def get_form_kwargs(self):
        kwargs = super(CreateTeacherView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class CreateStudentView(CreateView):
    template_name = 'accounts/create_student.html'
    form_class = StudentForm
    success_url = reverse_lazy('accounts:done')

    def get_form_kwargs(self):
        kwargs = super(CreateStudentView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class TeacherDetailView(DetailView):
    template_name = 'accounts/teacher_datail.html'
    model = User
    context_object_name = 'user'

accounts/templates/accounts/account_update.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="save">
    </form>
{% endblock %}

accounts/templates/accounts/create_student.html
{% extends 'base.html' %}
{% block content %}
 <form method="post" > 
 {% csrf_token %} 
  <div style="height: 950px;">
    <div class="sc-bwzfXH jNpIyI">
      <div class="row no-gutters" style="height: 170px;"></div>
    </div>
    <div class="sc-bwzfXH jNpIyI">
      <div
        class="row no-gutters"
        style="height: 30px; width: 100%; position: relative;"
      >
        <div style="position: absolute; left: 50%; transform: translateX(-50%);">
          <div
            style="height: 400px; width: 350px; border-radius: 7px; background-color: rgb(255, 255, 255); box-shadow: rgb(196, 196, 196) 0px 0px 50px 0px;"
          ></div>
        </div>
      </div>
    </div>
    <div class="sc-bwzfXH jNpIyI">
      <div class="row no-gutters" style="height: 70px;">
        <div class="col-sm-3"></div>
        <div class="col-sm-6" style="position: relative;">
          <div
            style="position: absolute; left: 50%; transform: translateX(-50%);"
          >
            <span
              style='font-size: 23px; font-family: "Cabin Condensed"; font-weight: 700; display: inline-block;'
              >학생 프로필</span
            >
          </div>
        </div>
      </div>
    </div>
    
    <div class="sc-bwzfXH jNpIyI">
      <div class="row no-gutters" style="height: 75px;">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
          <div style="position: relative;">
            <div
              style="width: 300px; height: 30px; border-radius: 0.375em; position: absolute; left: 50%; transform: translateX(-50%); display: block;"
            >
              <div style="display: block;">
                <span
                  style='margin-left: 5px; display: block; margin-top: 14px; font-family: "Cabin Condensed"; font-size: 13px; color: rgb(179, 179, 179);'
                  >학교</span
                >
              </div>
              <div
                style="width: 300px; height: 40px; background-color: rgb(250, 250, 250); border-radius: 0.375em; border-width: 1px; border-color: rgb(231, 231, 231); border-style: solid; display: block; margin-top: 5px;"
              >
                <input
                  type="text"
                  name="school"
                  required id="id_school"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="sc-bwzfXH jNpIyI">
      <div class="row no-gutters" style="height: 75px;">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
          <div style="position: relative;">
            <div
              style="width: 300px; height: 30px; border-radius: 0.375em; position: absolute; left: 50%; transform: translateX(-50%); display: block;"
            >
              <div style="display: block;">
                <span
                  style='margin-left: 5px; display: block; margin-top: 14px; font-family: "Cabin Condensed"; font-size: 13px; color: rgb(179, 179, 179);'
                  >학년</span
                >
              </div>
              <div
                style="width: 300px; height: 40px; background-color: rgb(250, 250, 250); border-radius: 0.375em; border-width: 1px; border-color: rgb(231, 231, 231); border-style: solid; display: block; margin-top: 5px;"
              >
                <input type="text" name="age" required id="id_age" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <br>
    <div class="sc-bwzfXH jNpIyI">
      <div class="row no-gutters" style="height: 5px;"></div>
    </div>
    <div class="sc-bwzfXH jNpIyI">
      <div class="row no-gutters" style="height: 70px;">
        <div class="col-sm-3"></div>
        <div class="col-sm-6" style="border-radius: 0.375px;">
          <div style="position: relative;">
            <div
              style="width: 300px; height: 40px; position: absolute; left: 50%; transform: translateX(-50%); background-color: rgb(243, 189, 39); border-radius: 3px; text-align: center; padding-top: 2px;"
            >
              <button type="submit">등록</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}
  

accounts/templates/accounts/create_teacher.html
{% extends 'base.html' %}
{% block content %}
 <form method="post" > 
 {% csrf_token %}
  <div style="height: 950px;">
    <div class="sc-bwzfXH jNpIyI">
      <div class="row no-gutters" style="height: 170px;"></div>
    </div>
    <div class="sc-bwzfXH jNpIyI">
      <div
        class="row no-gutters"
        style="height: 30px; width: 100%; position: relative;"
      >
        <div style="position: absolute; left: 50%; transform: translateX(-50%);">
          <div
            style="height: 400px; width: 350px; border-radius: 7px; background-color: rgb(255, 255, 255); box-shadow: rgb(196, 196, 196) 0px 0px 50px 0px;"
          ></div>
        </div>
      </div>
    </div>
    <div class="sc-bwzfXH jNpIyI">
      <div class="row no-gutters" style="height: 30px;">
        <div class="col-sm-3"></div>
        <div class="col-sm-6" style="position: relative;">
          <div
            style="position: absolute; left: 50%; transform: translateX(-50%);"
          >
            <span
              style='font-size: 23px; font-family: "Cabin Condensed"; font-weight: 700; display: inline-block;'
              >선생님 프로필</span
            >
          </div>
        </div>
      </div>
    </div>
    
    <div class="sc-bwzfXH jNpIyI">
      <div class="row no-gutters" style="height: 75px;">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
          <div style="position: relative;">
            <div
              style="width: 300px; height: 30px; border-radius: 0.375em; position: absolute; left: 50%; transform: translateX(-50%); display: block;"
            >
              <div style="display: block;">
                <span
                  style='margin-left: 5px; display: block; margin-top: 14px; font-family: "Cabin Condensed"; font-size: 13px; color: rgb(179, 179, 179);'
                  >학교</span
                >
              </div>
              <div
                style="width: 300px; height: 40px; background-color: rgb(250, 250, 250); border-radius: 0.375em; border-width: 1px; border-color: rgb(231, 231, 231); border-style: solid; display: block; margin-top: 5px;"
              >
                <input
                  type="text"
                  name="university"
                  required id="id_university"
                />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="sc-bwzfXH jNpIyI">
      <div class="row no-gutters" style="height: 75px;">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
          <div style="position: relative;">
            <div
              style="width: 300px; height: 30px; border-radius: 0.375em; position: absolute; left: 50%; transform: translateX(-50%); display: block;"
            >
              <div style="display: block;">
                <span
                  style='margin-left: 5px; display: block; margin-top: 14px; font-family: "Cabin Condensed"; font-size: 13px; color: rgb(179, 179, 179);'
                  >과목</span
                >
              </div>
              <div
                style="width: 300px; height: 40px; background-color: rgb(250, 250, 250); border-radius: 0.375em; border-width: 1px; border-color: rgb(231, 231, 231); border-style: solid; display: block; margin-top: 5px;"
              >
                <input type="text" name="subjects" required id="id_subjects"/>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="sc-bwzfXH jNpIyI">
      <div class="row no-gutters" style="height: 75px;">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
          <div style="position: relative;">
            <div
              style="width: 300px; height: 30px; border-radius: 0.375em; position: absolute; left: 50%; transform: translateX(-50%); display: block;"
            >
              <div style="display: block;">
                <span
                  style='margin-left: 5px; display: block; margin-top: 14px; font-family: "Cabin Condensed"; font-size: 13px; color: rgb(179, 179, 179);'
                  >나이</span
                >
              </div>
              <div
                style="width: 300px; height: 40px; background-color: rgb(250, 250, 250); border-radius: 0.375em; border-width: 1px; border-color: rgb(231, 231, 231); border-style: solid; display: block; margin-top: 5px;"
              >
                <input type="text" name="age" required id="id_age" />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    
    <br>
    <div class="sc-bwzfXH jNpIyI">
      <div class="row no-gutters" style="height: 5px;"></div>
    </div>
    <div class="sc-bwzfXH jNpIyI">
      <div class="row no-gutters" style="height: 70px;">
        <div class="col-sm-3"></div>
        <div class="col-sm-6" style="border-radius: 0.375px;">
          <div style="position: relative;">
            <div
              style="width: 300px; height: 40px; position: absolute; left: 50%; transform: translateX(-50%); background-color: rgb(243, 189, 39); border-radius: 3px; text-align: center; padding-top: 2px;"
            >
              <button type="submit">등록</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</form>
{% endblock %}
  

accounts/templates/accounts/logout.html
{% extends 'base.html' %}
{% block content %}
<h1>로그아웃되었습니다!</h1>
    <p><a href="{% url 'home' %}">로그인하러가기</a></p>
{% endblock%}

accounts/templates/accounts/signout.html
{% extends 'base.html' %}
{% block content %}
<h1>로그아웃되었습니다!</h1>
    <p><a href="{% url 'signin' %}">로그인하러가기</a></p>
{% endblock%}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% block content %}
<form method="post">
{% csrf_token %}
    <div style="height: 1100px;">
        <div class="sc-bwzfXH jNpIyI">
            <div class="row no-gutters" style="height: 100px;"></div>
        </div>
        <div class="sc-bwzfXH jNpIyI">
            <div class="row no-gutters" style="height: 30px; width: 100%; position: relative;">
                <div style="position: absolute; left: 50%; transform: translateX(-50%);">
                    <div style="height: 780px; width: 350px; border-radius: 7px; background-color: rgb(255, 255, 255); box-shadow: rgb(196, 196, 196) 0px 0px 50px 0px;"></div>
                </div>
            </div>
        </div>
        <div class="sc-bwzfXH jNpIyI">
            <div class="row no-gutters" style="height: 30px;">
                <div class="col-sm-3"></div>
                <div class="col-sm-6" style="position: relative;">
                    <div style="position: absolute; left: 50%; transform: translateX(-50%);">
                        <span style='font-size: 23px; font-family: "Cabin Condensed"; font-weight: 700; display: inline-block;'>회원가입</span>
                    </div>
                </div>
            </div>
        </div>
        <div class="sc-bwzfXH jNpIyI">
            <div class="row no-gutters" style="height: 90px;">
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                    <div style="position: relative;">
                        <div style="width: 300px; height: 30px; border-radius: 0.375em; position: absolute; left: 50%; transform: translateX(-50%); display: block;">
                            <div style="display: block;">
                                <span style='margin-left: 5px; display: block; margin-top: 14px; font-family: "Cabin Condensed"; font-size: 13px; color: rgb(179, 179, 179);'>아이디</span>
                            </div>
                            <div style="width: 300px; height: 40px; background-color: rgb(250, 250, 250); border-radius: 0.375em; border-width: 1px; border-color: rgb(231, 231, 231); border-style: solid; display: block; margin-top: 5px;">
                                <input type="text" name="username" required id="id_username" />
                            </div>
                            <span style='margin-left: 5px; display: block; font-family: "Cabin Condensed"; font-size: 12px; color: rgb(179, 179, 179); margin-top: 2px;'>150 characters or fewer. Letters, digits and @/./+/-/_
              only.</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="sc-bwzfXH jNpIyI">
            <div class="row no-gutters" style="height: 75px;">
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                    <div style="position: relative;">
                        <div style="width: 300px; height: 30px; border-radius: 0.375em; position: absolute; left: 50%; transform: translateX(-50%); display: block;">
                            <div style="display: block;">
                                <span style='margin-left: 5px; display: block; margin-top: 14px; font-family: "Cabin Condensed"; font-size: 13px; color: rgb(179, 179, 179);'>성명 ( 성 )</span>
                            </div>
                            <div style="width: 300px; height: 40px; background-color: rgb(250, 250, 250); border-radius: 0.375em; border-width: 1px; border-color: rgb(231, 231, 231); border-style: solid; display: block; margin-top: 5px;">
                                <input
                                        type="text"
                                        name="first_name"
                                        required
                                        id="id_first_name"
                                />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="sc-bwzfXH jNpIyI">
            <div class="row no-gutters" style="height: 75px;">
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                    <div style="position: relative;">
                        <div style="width: 300px; height: 30px; border-radius: 0.375em; position: absolute; left: 50%; transform: translateX(-50%); display: block;">
                            <div style="display: block;">
                                <span style='margin-left: 5px; display: block; margin-top: 14px; font-family: "Cabin Condensed"; font-size: 13px; color: rgb(179, 179, 179);'>성명 ( 이름 )</span>
                            </div>
                            <div style="width: 300px; height: 40px; background-color: rgb(250, 250, 250); border-radius: 0.375em; border-width: 1px; border-color: rgb(231, 231, 231); border-style: solid; display: block; margin-top: 5px;">
                                <input type="text" name="last_name" required id="id_last_name" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="sc-bwzfXH jNpIyI">
            <div class="row no-gutters" style="height: 75px;">
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                    <div style="position: relative;">
                        <div style="width: 300px; height: 30px; border-radius: 0.375em; position: absolute; left: 50%; transform: translateX(-50%); display: block;">
                            <div style="display: block;">
                                <span style='margin-left: 5px; display: block; margin-top: 14px; font-family: "Cabin Condensed"; font-size: 13px; color: rgb(179, 179, 179);'>이메일</span>
                            </div>
                            <div style="width: 300px; height: 40px; background-color: rgb(250, 250, 250); border-radius: 0.375em; border-width: 1px; border-color: rgb(231, 231, 231); border-style: solid; display: block; margin-top: 5px;">
                                <input type="text" name="email" required id="id_email" />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="sc-bwzfXH jNpIyI">
            <div class="row no-gutters" style="height: 90px;">
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                    <div style="position: relative;">
                        <div style="width: 300px; height: 30px; border-radius: 0.375em; position: absolute; left: 50%; transform: translateX(-50%); display: block;">
                            <div style="display: block;">
                                <span style='margin-left: 5px; display: block; margin-top: 14px; font-family: "Cabin Condensed"; font-size: 13px; color: rgb(179, 179, 179);'>비밀번호</span>
                            </div>
                            <div style="width: 300px; height: 40px; background-color: rgb(250, 250, 250); border-radius: 0.375em; border-width: 1px; border-color: rgb(231, 231, 231); border-style: solid; display: block; margin-top: 5px;">
                                <input
                                        type="password"
                                        name="password1"
                                        required
                                        id="id_password1"
                                />
                            </div>
                            <span style='margin-left: 5px; display: block; font-family: "Cabin Condensed"; font-size: 12px; color: rgb(179, 179, 179); margin-top: 2px;'>최소 8자 / 영문숫자혼합</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="sc-bwzfXH jNpIyI">
            <div class="row no-gutters" style="height: 75px;">
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                    <div style="position: relative;">
                        <div style="width: 300px; height: 30px; border-radius: 0.375em; position: absolute; left: 50%; transform: translateX(-50%); display: block;">
                            <div style="display: block;">
                                <span style='margin-left: 5px; display: block; margin-top: 14px; font-family: "Cabin Condensed"; font-size: 13px; color: rgb(179, 179, 179);'>비밀번호 재확인</span>
                            </div>
                            <div style="width: 300px; height: 40px; background-color: rgb(250, 250, 250); border-radius: 0.375em; border-width: 1px; border-color: rgb(231, 231, 231); border-style: solid; display: block; margin-top: 5px;">
                                <input
                                        type="password"
                                        name="password2"
                                        required
                                        id="id_password2"
                                />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="sc-bwzfXH jNpIyI">
            <div class="row no-gutters" style="height: 75px;">
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                    <div style="position: relative;">
                        <div style="width: 300px; height: 30px; border-radius: 0.375em; position: absolute; left: 50%; transform: translateX(-50%); display: block;">
                            <div style="display: block;">
                                <span style='margin-left: 5px; display: block; margin-top: 14px; font-family: "Cabin Condensed"; font-size: 13px; color: rgb(179, 179, 179);'>성</span>
                            </div>
                            <div style="width: 300px; height: 10px; background-color: transparent;   display: block; margin-top: 5px;">
                                <select style='font-family:"Cabin Condensed"; font-size:14px' name="sex" required="" id="id_sex" class="form-control">
                                    <option value="">선택 없음</option>

                                    <option value="0">남성</option>

                                    <option value="1">여성</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="sc-bwzfXH jNpIyI">
            <div class="row no-gutters" style="height: 75px;">
                <div class="col-sm-3"></div>
                <div class="col-sm-6">
                    <div style="position: relative;">
                        <div style="width: 300px; height: 30px; border-radius: 0.375em; position: absolute; left: 50%; transform: translateX(-50%); display: block;">
                            <div style="display: block;">
                                <span style='margin-left: 5px; display: block; margin-top: 14px; font-family: "Cabin Condensed"; font-size: 13px; color: rgb(179, 179, 179);'>신분</span>
                            </div>
                            <div style="width: 300px; height: 10px; background-color: transparent;    display: block; margin-top: 5px;">
                                <select style='font-family:"Cabin Condensed"; font-size:14px' name="user_type" required="" id="id_user_type" class="form-control">
                                    <option value="">선택 없음</option>

                                    <option value="0">선생님</option>

                                    <option value="1">학생</option>

                                    <option value="2">학부모</option> 
                                    
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="sc-bwzfXH jNpIyI">
            <div class="row no-gutters" style="height: 5px;"></div>
        </div>
        <p>
        <div class="sc-bwzfXH jNpIyI">
            <div class="row no-gutters" style="height: 70px;">
                <div class="col-sm-3"></div>
                <div class="col-sm-6" style="border-radius: 0.375px;">
                    <div style="position: relative;">
                        <div style="width: 300px; height: 40px; position: absolute; left: 50%; transform: translateX(-50%); background-color: rgb(243, 189, 39); border-radius: 3px; text-align: center; padding-top: 2px;">
                            <button type="submit">꿀과외 들어갈 준비완료</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </p>
         <div class="sc-bwzfXH jNpIyI">
            <div class="row no-gutters" style="height: 300px;"></div>
        </div>
    </div>
    <div class="sc-bwzfXH jNpIyI">
            <div class="row no-gutters" style="height: 300px;"></div>
        </div>
</form>

{% endblock %}

accounts/templates/accounts/signup_done.html
{% extends 'base.html' %}
{% block content %}
    <h2>회원가입이 완료되었습니다. </h2>
    <br>
    <a href="{% url 'home' %}">로그인하러가기!</a>
{% endblock %}

accounts/templates/accounts/teacher_datail.html
{% extends 'base.html' %}
{% block content %}
    {{ user.first_name }}
    {{ user.last_name }}
    {{ user.email }}
    {{ user.phone_number }}
    {% if user.is_teacher %}
    {{ user.teacher.university }}
    {{ user.teacher.age }}
    {{ user.teacher.subjects }}
    {% endif %}
    {{ user.student.school }}
    {{ user.student.year }}
{% endblock %}