advertise/urls.py
from django.urls import path
from advertise.views import *

app_name = "advertise"

urlpatterns = [
    path('', AdvertiseIndexView.as_view(), name='index'),
    path('search/', AdvertiseSearchFormView.as_view(), name='search'),
    path('<int:pk>/', AdvertiseDetailView.as_view(), name='detail'),
    path('create/', AdvertiseCreateView.as_view(), name='create'),
    path('<int:pk>/update/', AdvertiseUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', AdvertiseDelete, name='delete'),
    path('condition/', ClassifiedIndexView.as_view(), name='classified'),
    path('region/', RegionView, name='region'),
]

advertise/templates/advertise/advertise_home.html
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>

    <h1>메인 홍보 페이지</h1>


    <form method="post" action="{% url 'advertise:search' %}">
        {% csrf_token %}
        <input type='text' name="search_word" placeholder="검색">
        <input class="button" type='submit' value="검색">
    </form>



    <p>
        <a class="btn btn-light" data-toggle="collapse" href="#filterform" role="button" aria-expanded="false" aria-controls="filterform">
            FILTER
        </a>
    </p>
    <div class="collapse" id="filterform">
        <form method="get" action="{% url 'advertise:classified' %}" style="width:50%; margin-left:5%">
            
            <div class="form-group row">
                <label for="inputname" class="col-sm-2 col-form-label">선생님 이름</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" name = "name" id="inputname" placeholder="선생님 이름">
                </div>
            </div>
            <fieldset class="form-group">
                <div class="row">
                    <legend class="col-form-label col-sm-2 pt-0">선생님 성별</legend>
                    <div class="col-sm-10">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="gridcheckbox1" name = "sex" value="남성">
                            <label class="form-check-label" for="gridcheckbox1">
                                남성
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="gridcheckbox2" name = "sex" value="여성">
                            <label class="form-check-label" for="gridcheckbox2">
                                여성
                            </label>
                        </div>
                    </div>
                </div>
            </fieldset>
            <div class="form-group row">
                <div class="col-sm-10">
                    <label class="my-1 mr-2" for="inlineFormCustomSelectPref">수강 과목</label>
                    <select name = "subject" style="width:30%" class="custom-select my-1 mr-sm-2" id="inlineFormCustomSelectPref">
                        <option selected>선택 없음</option>
                        <option value="국어">국어</option>
                        <option value="수학">수학</option>
                        <option value="영어">영어</option>
                    </select>
                </div>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label for="inputState">수강 지역[도, 특별(광역)시]</label>

                        <select name="region_1" id="inputState" class="custom-select my-1 mr-sm-2">
                            <option selected>선택 없음</option>
                            {% for regions in regions %}
                                <option value="{{ regions }}_region_id">{{regions}}</option>
                            {% endfor %}
                        </select>

                </div>
            </div>
            <div class="form-group col-md-6">
                <label for="inputCountry">수강 지역[구, 시]</label>
                <select name="region_2" id="inputCountry" class="custom-select my-1 mr-sm-2">
                    <option selected>선택 없음</option>
                    {% for classified_regions in regions.classified_region.all%}
                        <option value="{{ classified_regions }}">{{ classified_regions }}</option>
                    {% endfor %}
                </select>
            </div>
    </div>
    <div class="form-group row">
        <div class="col-sm-10">
            <button type="submit" class="btn btn-primary">검색</button>
        </div>
    </div>
    </form>
    </div>

    {% block extra_scripts %}
        <script type="text/javascript">
            $(document).ready(function () {
                $('#_region_id').click(function () {
                    var region = $('#{{ regions }}').val();
                    $.ajax({
                        url: "{% url 'advertise:region' %}",
                        data: {
                            "region": region
                        },
                        success: function (data) {
                            alert('성공');
                        },
                        error: function () {
                            alert('실패');
                        }
                    });
                });
            });
        </script>
    {% endblock %}


    <p>
        {%if query %}
            {% if context %}
                {% for list in context %}
                    <li><a href="{% url 'advertise:detail' list.id%}">{{ list.title }}{{ list.author }}{{ list.created_date }}</a></li>
                {% endfor %}
            {% else %}
                <p>검색 결과가 없습니다.</p>
            {%endif%}
        {%endif%}
    </p>

    <p>전체글 목록
        {%if object_list%}
            {% for post in object_list %}
                <li><a href="{% url 'advertise:detail' post.id%}">{{ post.title }}{{ post.author }}{{ post.created_date }}</a></li>
            {% endfor %}
        {%else%}
            <p>등록된 글이 없습니다.</p>
        {% endif %}
    </p>

    <p><a href ="{% url 'advertise:create' %}">등록하기</a> </p>

advertise/templates/advertise/advertise_search.html
<h1>검색 페이지</h1>



<form method="POST" action="{% url 'advertise:search' %}">
    {% csrf_token %}
    <input type='text' name='search_word' placeholder="검색">
    <input class="button" type='submit' value="검색">
</form>

{%if object_list%}
    {% for search in object_list %}
        <li><a href="{% url 'advertise:detail' search.id%}">{{search.title}}</a></li>
        <li><a href="{% url 'accounts:teacher_datail' search.author.id %}">{{ search.author }}</a></li>
    {% endfor %}
{% else %}
    <p>검색 결과가 없습니다.</p>
{% endif %}

advertise/templates/advertise/post_detail.html
<head>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>

<h1>디테일 페이지</h1>
{{object.title}}
{{object.region}}
{{object.subject}}
{{object.content}}
<a href = "{% url 'advertise:update' post.id%}">수정하기</a>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#deleteModal">
  삭제하기
</button>


{% comment %} <a href = "{% url 'advertise:delete' post.id%}">삭제하기</a> {% endcomment %}
<a href = "{% url 'advertise:index'%}">목록으로</a>


<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Delete</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        글을 삭제하시겠습니까?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
        <input class="btn btn-success" type="button" value="삭제" onclick="location.href='{% url 'advertise:delete' post.id%}'">
      </div>
    </div>
  </div>
</div>

advertise/templates/advertise/post_form.html
 <form method="post" enctype=multipart/form-data action="{% url 'advertise:create' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
 </form>

advertise/templates/advertise/post_update.html
{% extends 'base.html' %}
{% block content %}
<form method="post" action="{% url 'advertise:update' post.id%}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Create</button>
 </form>
{% endblock %}