accounts/urls.py
from django.urls import path
from accounts.views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', CreateUserView.as_view(), name='signup'),
    path('done/', CreateDoneUserView.as_view(), name='done'),
    path('createTeacher/', CreateTeacherView.as_view(), name='teacher'),
    path('createStudent/', CreateStudentView.as_view(), name='student'),
    path('edit/<int:pk>', UpdateUserView.as_view(), name='edit'),
    path('<int:pk>/', TeacherDetailView.as_view(), name='teacher_datail'),
]

classes/urls.py
from django.urls import path
from .views import *

app_name = 'classes'

urlpatterns = [
     path('', ClassesListView.as_view(), name='index'),
     path('<int:class_id>', ClassDetailView.as_view(), name='detail'),
     path('create/', ClassCreateView.as_view(), name='create'),
     path('studentcheck/', StudentIdCheck, name='student_check'),
     path('<int:class_id>/schedules/create/', ScheduleCreateView.as_view(), name='schedule_create'),
     path('<int:class_id>/memo/create/', MemoCreateView.as_view(), name='memo_create'),
     path('<int:class_id>/delete/', ClassDeleteView.as_view(), name='delete'),
     path('<int:class_id>/schedules/<int:schedule_id>/delete/', ScheduleDeleteView.as_view(), name='schedule_delete'),
     path('<int:class_id>/memo/<int:memo_id>/delete/', MemoDeleteView.as_view(), name='memo_delete'),
]

honey/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from honey.views import *
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', SignInView.as_view(), name='signin'),
    path('signout/', SignOutView.as_view(), name='signout'),
    path('home/', HomeView.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('advertise/', include('advertise.urls', namespace='advertise')),
    path('question/',include('question.urls',namespace='question')),
    path('classes/', include('classes.urls', namespace='classes')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()

notice/urls.py
from django.urls import path
from .views import *

app_name = 'notice'

urlpatterns = [
    path('index/', NoticeIndexView.as_view(), name='post_index'),
    path('index/<int:pk>/', NoticeDetailView.as_view(), name='post_detail'),
    path('create/', NoticeCreateView.as_view(), name='post_create'),
    path('index/<int:pk>/update', NoticeUpdateView.as_view(), name='post_update'),
    path('index/<int:pk>/delete', NoticeDelete, name='post_delete'),
]

question/urls.py
from django.urls import path
from .views import *

app_name = 'notice'

urlpatterns = [
    path('', QuestionListView.as_view(), name='question_index'),
    path('board/answer/<int:pk>',AnswerRegisterView.as_view(), name = 'answer_register'),
    path('board/', QuestionView.as_view(), name='question_register'),
    path('board/<int:pk>/edit', QuestionEditView.as_view(), name='question_edit'),
    path('board/<int:pk>/delete', QuestionDeleteView.as_view(), name='question_delete'),

]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <link rel="stylesheet" type="text/css" href="{% static 'honey/css/style.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'honey/css/style1.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR:100,300,400,500,700,900&display=swap&subset=korean" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    {% block extra_styles %}
    {% endblock %}
    {% block extra_scripts %}
    {% endblock %}
    <title>{% block title %}HoneyTutoring{% endblock %}</title>
</head>
<body>
{% block content %}
{% endblock %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% block content %}
    <h1>HELLO HONEY TUTORING</h1>
        {% if user.is_authenticated %}
            <a href="">HI {{ user.username }}</a>
            <p><a href="{% url 'signout' %}">logout</a></p>
            {% comment %} <p><a href="{% url 'accounts:passwordreset' %}">reset password</a></p> {% endcomment %}
            <p><a href = "{% url 'accounts:edit' user.id %}"> 내 정보 수정하기 </a></p>
            <a href="{% url 'notice:post_index' %}">공지사항</a>
            <br>
            <a href="{% url 'advertise:index' %}">홍보게시판</a>
            <br>
            <p><a href="{% url 'question:question_index' %}">Q&A</a></p>
            <a href="{% url 'classes:index' %}">관리</a>
        {% else %}
            <br>
            <form method="post" action="{% url 'home' %}">
                {% csrf_token %}
                {{ form.as_p }}
            <input type="submit" value="login" />
            </form>
            <p>아이디가 없으신가요? <a href="{% url 'accounts:signup' %}">회원가입하러가기</a></p>
        {% endif %}


{#    {% if user.is_authenticated %}#}
{#    Hi {{ user.username }}!#}
{#    <p><a href="{% url 'signout' %}">logout</a></p>#}
{#    {% else %}#}
{#    <p>You are not logged in</p>#}
{#    <a href="{% url 'home' %}">login</a>#}
{#    {% endif %}#}
{#    <br>#}
{#    <a href="{% url 'notice:post_index' %}">공지사항</a>#}

{% endblock %}

templates/signin.html
{% extends 'base.html' %}
{% load static %}
{% block extra_styles %}
    <style>
        body {
            background-color: white;
        }

        input {
            width: 100%;
            margin-left: 5px;
            /* display: block; */
            margin-top: 7px;
            font-family: "Cabin Condensed";
            font-size: 13px;
            background-color: transparent;
            border-color: transparent;
        }
        input:focus {
            outline: none !important;
        }

        button {
            font-size: 18px;
            font-weight: 500;
            font-family: "Cabin Condensed";
            color: rgb(255, 255, 255);
            height: 100%;
            width: 100%;
            background-color: transparent;
            border-color: transparent;
        }
        ::placeholder {
            color: rgb(179, 179, 179);
        }

        select {
            background-color: rgb(255, 255, 255);
        }
        .texttrigger:hover .texttarget {
            color: #f9c700 !important;
            transition: 0.15s all ease;
        }

        .texttarget {
            transition: 0.25s all ease;
        }

        .menutrigger:hover .menutarget {
            display: block;
            opacity: 1;
        }

        .menutarget {
            display: none;
            opacity: 0;
            transition: 2s all ease-in-out;
        }
    </style>
{% endblock %}

{% block content %}
    <div id="content">
    <div>
    </div>
    <div>
    {% if user.is_authenticated %}
        HI {{ user.username }}
        <p><a href="{% url 'signout' %}">logout</a></p>
        <p><a href="{% url 'accounts:edit' user.id %}">내 정보 수정하기</a></p>
    {% else %}
        <div>
        {#                <form method="post" action="{% url 'home' %}">#}
        {#                    {% csrf_token %}#}
        {#                    <p>#}
        {#                        <label for="id_username"></label>#}
        {#                        <input type="text" name="username" autofocus required id="id_username" placeholder="아이디">#}
        {#                    </p>#}
        {#                    <p>#}
        {#                        <label for="id_password"></label>#}
        {#                        <input type="password" name="password" required id="id_password" placeholder="비밀번호">#}
        {#                    </p>#}
        {#                    <button type="submit">로그인</button>#}
        {#                </form>#}
        {#            <a href="{% url 'accounts:signup' %}">회원가입하러가기~</a>#}
        {#            </div>#}
        {#            </div>#}
        {#            </div>#}

        <div style="height: 800px;">
            <div class="sc-bwzfXH jNpIyI">
                <div class="row no-gutters" style="height: 160px;"></div>
            </div>
            <div class="sc-bwzfXH jNpIyI">
                <div class="row no-gutters" style="height: 50px; width: 100%; position: relative;">
                    <div style="position: absolute; left: 50%; transform: translateX(-50%);">
                        <div style="height: 460px; width: 350px; border-radius: 7px; background-color: rgb(255, 255, 255); box-shadow: rgb(196, 196, 196) 0px 0px 50px 0px;"></div>
                    </div>
                </div>
            </div>
            <div class="sc-bwzfXH jNpIyI">
                <div class="row no-gutters" style="height: 30px;">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-6" style="position: relative;">
                        <div style="position: absolute; left: 50%; transform: translateX(-50%);">
                            <span style='font-size: 30px; font-family: "Cabin Condensed"; font-weight: 700; display: inline-block; color: rgb(243, 189, 39);'>꿀</span><span style='font-size: 30px; font-family: "Cabin Condensed"; font-weight: 700; display: inline-block;'>과외</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="sc-bwzfXH jNpIyI">
                <div class="row no-gutters" style="height: 50px;"></div>
            </div>
            <form method="post" action="{% url 'home' %}">
                {% csrf_token %}
                <div class="sc-bwzfXH jNpIyI">
                    <div class="row no-gutters" style="height: 50px;">
                        <div class="col-sm-3"></div>
                        <div class="col-sm-6">
                            <div style="position: relative;">
                                <div style="width: 300px; height: 40px; background-color: rgb(250, 250, 250); border-radius: 0.375em; position: absolute; left: 50%; transform: translateX(-50%); border-width: 1px; border-color: rgb(231, 231, 231); border-style: solid; padding-left: 5px;">
                                    <input
                                            type="text"
                                            name="username"
                                            autofocus
                                            required
                                            id="id_username"
                                            placeholder="아이디"
                                    />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="sc-bwzfXH jNpIyI">
                    <div class="row no-gutters" style="height: 50px; margin-top: 5px;">
                        <div class="col-sm-3"></div>
                        <div class="col-sm-6">
                            <div style="position: relative;">
                                <div style="width: 300px; height: 40px; background-color: rgb(250, 250, 250); border-radius: 0.375em; position: absolute; left: 50%; transform: translateX(-50%); border-width: 1px; border-color: rgb(231, 231, 231); border-style: solid; padding-left: 5px;">
                                    <!-- <span
                                      style='margin-left: 5px; display: block; margin-top: 14px; font-family: "Cabin Condensed"; font-size: 13px; color: rgb(179, 179, 179);'
                                      >비밀번호</span
                                    > -->
                                    <input
                                            type="password"
                                            name="password"
                                            required
                                            id="id_password"
                                            placeholder="비밀번호"
                                    />
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="sc-bwzfXH jNpIyI">
                    <div class="row no-gutters" style="height: 70px;">
                        <div class="col-sm-3"></div>
                        <div class="col-sm-6" style="border-radius: 0.375px; position: relative;">
                            <div style="width: 300px; height: 40px; position: absolute; transform: translateX(-50%); background-color: rgb(243, 189, 39); border-radius: 3px; text-align: center; left: 50%; padding-top: 2px; margin-top: 5px;">
                                <button type="submit">로그인</button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
            <div class="sc-bwzfXH jNpIyI">
                <div class="row no-gutters" style="height: 40px;">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-6" style="border-radius: 0.375px;">
                        <div style="width: 100%; height: 100%; text-align: center; padding-top: 10px;">
                            <span style='font-size: 15px; font-weight: 400; font-family: "Cabin Condensed"; color: rgb(104, 104, 104);'>계정이 없으신가요?</span>
                        </div>
                    </div>
                    <div class="col-sm-3"></div>
                </div>
            </div>
            <div class="sc-bwzfXH jNpIyI">
                <div class="row no-gutters" style="height: 70px;">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-6" style="border-radius: 0.375px;">
                        <a href="{% url 'accounts:signup' %}"><div style="position: relative;">
                            <div style="width: 300px; height: 40px; position: absolute; left: 50%; transform: translateX(-50%); background-color: rgb(243, 189, 39); border-radius: 3px; text-align: center; padding-top: 10px;">
                                <span style='font-size: 18px; font-weight: 500; font-family: "Cabin Condensed"; color: rgb(255, 255, 255);'>회원가입</span>
                            </div>
                        </div></a>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}


{% endblock %}