classes/urls.py
from django.urls import path
from .views import *

app_name = 'classes'

urlpatterns = [
     path('', ClassesListView.as_view(), name='index'),
     path('<int:class_id>', ClassDetailView.as_view(), name='detail'),
     path('create/', ClassCreateView.as_view(), name='create'),
     path('studentcheck/', StudentIdCheck, name='student_check'),
     path('<int:class_id>/schedules/create/', ScheduleCreateView.as_view(), name='schedule_create'),
     path('<int:class_id>/memo/create/', MemoCreateView.as_view(), name='memo_create'),
     path('<int:class_id>/delete/', ClassDeleteView.as_view(), name='delete'),
     path('<int:class_id>/schedules/<int:schedule_id>/delete/', ScheduleDeleteView.as_view(), name='schedule_delete'),
     path('<int:class_id>/memo/<int:memo_id>/delete/', MemoDeleteView.as_view(), name='memo_delete'),
]

classes/models.py
from django.db import models


class Class(models.Model):
    class_teacher = models.ForeignKey('accounts.Teacher', on_delete=models.CASCADE, related_name='classes', null=True)
    students = models.ManyToManyField('accounts.Student', related_name='classes')
    class_name = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    subject = models.CharField(max_length=5)
    etc = models.CharField(max_length=200, blank=True, default='')
    create_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.class_name


class Schedule(models.Model):
    klass = models.ForeignKey('classes.Class', on_delete=models.CASCADE, related_name='schedules')
    start_date = models.DateField()
    end_date = models.DateField()
    name = models.CharField(max_length=250)

    def __str__(self):
        return self.name


class Memo(models.Model):
    klass = models.ForeignKey('classes.Class', on_delete=models.CASCADE, related_name='memo')
    content = models.CharField(max_length=250)

    def __str__(self):
        return self.content

classes/forms.py
from django import forms
from .models import Class, Schedule, Memo


class ClassCreateForm(forms.ModelForm):
    class Meta:
        model = Class
        fields = (
            'class_name',
            'description',
            'subject',
            'etc',
        )

    def __init__(self, class_teacher, *args, **kwargs):
        self.class_teacher = class_teacher
        super(ClassCreateForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        self.instance.class_teacher = self.class_teacher
        return super(ClassCreateForm, self).save(commit=commit)


class ScheduleCreateForm(forms.ModelForm):
    class Meta:
        model = Schedule
        exclude = ('klass',)
        fields = '__all__'

    def __init__(self, klass_id, *args, **kwargs):
        self.klass_id = klass_id
        super(ScheduleCreateForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        self.instance.klass_id = self.klass_id
        return super(ScheduleCreateForm, self).save(commit=commit)


class MemoCreateForm(forms.ModelForm):
    class Meta:
        model = Memo
        exclude = ('klass',)
        fields="__all__"

    def __init__(self, klass_id, *args, **kwargs):
        self.klass_id = klass_id
        super(MemoCreateForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        self.instance.klass_id = self.klass_id
        return super(MemoCreateForm, self).save(commit=commit)

classes/views.py
from django.http import JsonResponse, Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView, CreateView, DeleteView
from django.contrib import messages
from accounts.models import User
from .forms import *
from .models import *
from pure_pagination.mixins import PaginationMixin


class ClassesListView(PaginationMixin, ListView):
    template_name = 'classes/class_list.html'
    model = Class
    paginate_by = 3

    def get_queryset(self):
        queryset = super(ClassesListView, self).get_queryset()
        if User.USER_TEACHER == self.request.user.user_type:
            teacher_classes = self.request.user.teacher.classes.all()
            return teacher_classes
        elif User.USER_STUDENT == self.request.user.user_type:
            student_classes = self.request.user.student.classes.all()
            return student_classes
        # elif Users.USER_PARENT == self.request.user.user_type:
        #     retu


class ClassDetailView(DetailView):
    template_name = 'classes/class_detail.html'
    model = Class
    pk_url_kwarg = 'class_id'

    def get_context_data(self, **kwargs):
        context = super(ClassDetailView, self).get_context_data(**kwargs)
        context['memo_list'] = self.object.memo
        return context


class ScheduleCreateView(CreateView):
    template_name = 'classes/class_detail.html'
    model = Schedule
    pk_url_kwarg = 'class_id'
    form_class = ScheduleCreateForm

    def get_success_url(self):
        class_id = self.kwargs.get('class_id')
        return reverse_lazy('classes:detail', kwargs={'class_id': class_id})

    def get(self, request, *args, **kwargs):
        raise Http404

    def form_invalid(self, form):
        messages.add_message(self.request, messages.ERROR, '올바르지 않은 스케줄입니다.')
        return HttpResponse(self.get_success_url())

    def get_form_kwargs(self):
        kwargs = super(ScheduleCreateView, self).get_form_kwargs()
        kwargs['klass_id'] = self.kwargs.get('class_id')
        return kwargs


class MemoCreateView(CreateView):
    template_name = 'classes/class_detail.html'
    model = Memo
    form_class = MemoCreateForm
    pk_url_kwarg = 'class_id'

    def post(self, request, *args, **kwargs):
        return super(MemoCreateView, self).post(request, *args, **kwargs)

    def get_success_url(self):
        class_id = self.kwargs.get('class_id')
        return reverse_lazy('classes:detail', kwargs={'class_id': class_id})

    def get(self, request, *args, **kwargs):
        raise Http404

    def get_form_kwargs(self):
        kwargs = super(MemoCreateView, self).get_form_kwargs()
        kwargs['klass_id'] = self.kwargs.get('class_id')
        return kwargs


class ClassCreateView(CreateView):
    template_name = 'classes/class_create.html'
    form_class = ClassCreateForm
    success_url = reverse_lazy('classes:index')

    def get_form_kwargs(self):
        kwargs = super(ClassCreateView, self).get_form_kwargs()
        kwargs['class_teacher'] = self.request.user.teacher
        return kwargs

    def form_valid(self, form):
        self.object = form.save()

        students = self.request.POST.getlist('students')
        students = list(filter(lambda x: x, students))

        self.object.students.add(*students)

        return HttpResponseRedirect(self.get_success_url())


class ClassDeleteView(DeleteView):
    pass


class ScheduleDeleteView(DeleteView):
    template_name = 'classes/class_detail.html'
    model = Schedule
    pk_url_kwarg = 'schedule_id'

    def get_success_url(self):
        class_id = self.kwargs.get('class_id')
        return reverse_lazy('classes:detail', kwargs={'class_id': class_id})

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)


class MemoDeleteView(DeleteView):
    template_name = 'classes/class_detail.html'
    model = Memo
    pk_url_kwarg = 'memo_id'


@csrf_exempt
def StudentIdCheck(request, *args, **kwargs):
    user_name = request.GET.get('name')
    student_user = get_object_or_404(User, username=user_name)

    if hasattr(student_user, 'student'):
        return JsonResponse({'student_id': student_user.student.id})
    raise Http404

classes/templates/classes/class_create.html
{% extends 'base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="field-input">
            <label class="col-md-3" for="id_class_name">Class 이름</label> <input class="col-md-9" type="text" name="class_name" maxlength="15" required="" id="id_class_name">
        </div>
        <div class="field-input">
            <label class="col-md-3" for="id_description">요약</label> <input class="col-md-9" type="text" name="description" maxlength="13" required="" id="id_description">
        </div>
        <div class="field-input">
            <label class="col-md-3" for="subject">과목</label> <input class="col-md-9" type="text" name="subject" required="" id="id_description">
        </div>
        <div class="field-input">
            <label class="col-md-3" for="id_etc">기타 사항</label> <input class="col-md-9" type="text" name="etc" maxlength="254" id="id_etc">
        </div>

        <div class="field-input">
            <label class="col-md-3">학생 ID</label>
            <input class="col-md-9" type="text" maxlength="150" id="studentNameInput">
            <button id="searchStudentName" type="button">확인</button>
            <div id="studentFormWrapper">

            </div>
            <div id="studentForm" style="display: none;">
                <input readonly class="student-name-input">
                <input class="student-id-input" name="students" style="visibility: hidden;">
                <button class="student-delete-btn" type="button">삭제</button>
            </div>
        </div>

        <div class="row">
            <button type="submit" class="pull-right">제출</button>
        </div>
    </form>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $('body').on('click', '.student-delete-btn', function () {
                $(this).parent().remove();
            });

            $('#searchStudentName').click(function () {
                var name = $('#studentNameInput').val();
                $.ajax({
                    url: "{% url 'classes:student_check' %}",
                    data: {
                        "name": name
                    },
                    success: function (data) {
                        var student_id = data['student_id'];

                        var $newStudentForm = $('#studentForm').clone();
                        $newStudentForm.children('.student-name-input').val(name);
                        $newStudentForm.children('.student-id-input').val(student_id);
                        $('#studentNameInput').val('');
                        $('#studentFormWrapper').append($newStudentForm);
                        $newStudentForm.show();

                        $newStudentForm.children('student-delete-btn').click(function () {
                            $(this).parent().remove();
                        });
                    },
                    error: function () {
                        alert('존재하지 않는 학생 ID 입니다.');
                    }
                });
            });
        });
    </script>

{% endblock %}

classes/templates/classes/class_detail.html
{% extends 'base.html'%}
{% load static %}

{% block extra_styles %}
    <link href='{% static 'vendor/fullcalendar/core/main.css' %}' rel='stylesheet' />
    <link href='{% static 'vendor/fullcalendar/daygrid/main.css' %}' rel='stylesheet' />

{% endblock %}

{% block extra_scripts %}

    <script src="{% static 'vendor/fullcalendar/core/main.js' %}"></script>
    <script src="{% static 'vendor/fullcalendar/daygrid/main.js' %}"></script>
    <script src="{% static 'vendor/fullcalendar/interaction/main.js' %}"></script>
    <script src="{% static 'vendor/fullcalendar/moment/main.js' %}"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            var calendarEl = document.getElementById('calendar');
            var calendar = new FullCalendar.Calendar(calendarEl, {
                plugins: ['dayGrid', 'interaction', 'moment'],
                defaultView: 'dayGridMonth',
                selectable: true,
                events: [
                    {% for schedule in object.schedules.all %}
                        {
                            id: {{ schedule.id }},
                            title: '{{ schedule.name }}',
                            start: '{{ schedule.start_date|date:"c" }}',
                            end: '{{ schedule.end_date|date:"c" }}',
                        },
                    {% endfor %}
                ],
                eventClick: function (info) {
                    if (confirm(info.event.title + '을(를) 삭제하시겠습니까?')) {
                        document.location.href += '/schedules/' + info.event.id + '/delete/';
                    }
                },
                select: function (selectionInfo) {
                    var input = prompt('일정 제목을 입력하세요 !');
                    if (input) {
                        document.getElementById('name').value = input;
                        document.getElementById('start_date').value = selectionInfo.startStr;
                        document.getElementById('end_date').value = selectionInfo.endStr;
                        document.getElementById("event_form").submit();
                    }
                }
            });
            calendar.render();
        });
    </script>
{% endblock %}
{% block content %}
    <div style="max-width:900px; margin:0 auto; float: left" id='calendar'></div>
    <form action="{% url 'classes:schedule_create' object.id %}" method="post" id="event_form">
        {% csrf_token %}
        <input type="hidden" name="name" id="name">
        <input type="hidden" name="start_date" id="start_date">
        <input type="hidden" name="end_date" id="end_date">
    </form>
    <div style="float:right;">
        {% for memo in memo_list.all %}
            <p id="memo">{{ memo.content }}</p>
        {% endfor %}

    </div>

    <form method="post" action="{% url 'classes:memo_create' object.id  %}">
        {% csrf_token %}
        <div class="field-input" style="float: right">
            <label class="col-md-3" for="id_content"></label> <input class="col-md-9" type="text" maxlength="250" name="content" id="id_content"/>
            <button type="submit" value="메모생성">메모생성</button>
        </div>
    </form>

    <div>
        <h1>
            학생
            {% for student in object.students.all %}
                <p>{{ student }}</p>
            {% endfor %}
        </h1>
        <h1>
            선생님
            <p>
                {{ object.class_teacher }}
            </p>
        </h1>
    </div>
    <div>
        <h1>
            메모
        </h1>
        <div>
            {% for memo in object.memos.all %}
                <p>{{ memo }}</p>
            {% endfor %}
        </div>
    </div>


{#    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>#}
{#    <script type="text/javascript">#}
{#        $(function () {#}
{#            $('#memo').click(function () {#}
{#                var memo = $('#memo').val();#}
{#                $.ajax({#}
{#                    url: "{% url 'classes:memo_delete' memo.id %}",#}
{#                    data: {#}
{#                        "memo": memo#}
{#                    },#}
{#                    success: function () {#}
{#                        alert('삭제되었습니다.');#}
{#                    },#}
{#                    error: function () {#}
{#                        alert('실패');#}
{#                    }#}
{#                });#}
{#            });#}
{#        });#}
{#    </script>#}

{% endblock %}

classes/templates/classes/class_list.html
{% extends 'base.html' %}
{% block content %}

    <a href="{% url 'classes:create' %}">만들기</a>

    {% for class in object_list.all %}
        <li><a href="{% url 'classes:detail' class.id %}">{{ class.class_name }}</a></li>
    {% endfor %}


    {% include "classes/class_pagination.html" %}

{% endblock %}

classes/templates/classes/class_pagination.html
{% load i18n %}
<div class="pagination">
    {% if page_obj.has_previous %}
        <a href="?{{ page_obj.previous_page_number.querystring }}" class="prev">&lsaquo;&lsaquo; {% trans "previous" %}</a>
    {% else %}
        <span class="disabled prev">&lsaquo;&lsaquo; {% trans "previous" %}</span>
    {% endif %}
    {% for page in page_obj.pages %}
        {% if page %}
            {% ifequal page page_obj.number %}
                <span class="current page">{{ page }}</span>
            {% else %}
                <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
            {% endifequal %}
        {% else %}
            ...
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <a href="?{{ page_obj.next_page_number.querystring }}" class="next">{% trans "next" %} &rsaquo;&rsaquo;</a>
    {% else %}
        <span class="disabled next">{% trans "next" %} &rsaquo;&rsaquo;</span>
    {% endif %}
</div>